#:kivy 2.1.0

<MainScreen>:
    FloatLayout:
        pos: 0,0
        size: root.width, root.height

        GridLayout:
            cols: 1
            pos_hint:{'x':.1,'y':.1}
            size_hint: .8, .8
            
            TextInput:
                id: text_in
                text: ""
                size_hint_y: None
                height:200

            TextInput:
                id: my_text
                text: ""
                multiline: False
                size_hint_y: None
                height:100

            Button:
                id: my_button
                on_press: root.send_message()  # We need to call root, and then call the function to send something.
                text: "Send"
                size_hint_y: None
                height:100
